export const REQUEST_TRIVIA_QUESTIONS = 'REQUEST_TRIVIA_QUESTIONS';
export const GET_TRIVIA_QUESTIONS = 'GET_TRIVIA_QUESTIONS';

export const GET_PLAYER_INFO = 'GET_PLAYER_INFO';

export const GET_FETCH_ERROR = 'GET_FETCH_ERROR';

export const UPDATE_SCORE = 'UPDATE_SCORE';
export const UPDATE_QUESTION = 'UPDATE_QUESTION';
export const SET_ANSWER_TIME = 'SET_ANSWER_TIME';

export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const UPDATE_CONFIG = 'UPDATE_CONFIG';
